### ISSUE TITLE
Neue(s) Event(s) - LabyModApi

### ISSUE THREAD

**Issue by minelucraft** [LabyMod/legacy-labymod-server-api#1]
Hey,
da auf docs.labymod.net steht, dass man bei weiteren benötigten Events hier eine Issue schreiben soll, mach ich es auch, obwohl ich finde, dass das mehr mit dem Client als mit der ServerApi zu tun hat.

Also, ist mir nur so in den Sinn gekommen, aber man könnte doch einfach ein Package Send / Recieve Event erstellen, woraus man auch viele eigene Events ohne ASM erstellen kann.
Zusätzlich vielleicht noch, dass es einen Boolean returnt (true = senden/empfangen, false = nicht senden / nicht im code weitermachen)

Und ein Channel im Discord wäre vielleicht ganz cool für Vorschläge, weil ja guut, das hier hat eher weniger mit der ServerApi zu tun xd.

**Comment by scrummer** [comment]
Hi there!

First of all: We've got a developer discord where such stuff can be discussed: https://labymod.net/devcord

The event you said would be a completely new event (which doesn't really make sense). The note on our documentation page said that you can ask here for implementing other (currently not implemented) forge events which can be accessed from the API.

In your special case: Maybe discuss it on our developer discord in the #general or #help channel.

Cheers, Scrummer
