### ISSUE TITLE
Using my selfwritten 'server' api

### ISSUE THREAD

**Issue by manuelkollus** [LabyMod/legacy-labymod-server-api#4]
Hello dear LabyMod Team,
i have recently written a new 'server' interface for you, as the current one has not been well implemented. In the near future, I will offer the Discord support and much more...
I'd like to get in touch with them, because I have some more things to say about the 'server' implementation, my name on Discord is 'Manuel#1335'.

I already wanted to get in touch with Daniel (LabyStudio), but he didn't reply.

Here is the link to the repository:
https://github.com/manuelkollus/labymod-server

Yours sincerely,
Manuel Kollus 

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes (partly)
| BC Break report? | no
| RFC?             | no

**Comment by scrummer** [comment]
It would be great if you could fork this repo and make a pull request with your implementation. We could maintain it better then and the flair of the "community driven" project wouldn't be lost.

We can discuss a further collaboration. IMO you're very active here and a collaboration would make sense here.
